config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  root to: 'blog/posts#index'

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
  	resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
  	get 'about' => 'pages#about', as: :about
  	get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :post       

  validates_presence_of :name, on: :update

  def change_password(attrs)
    update(password: attrs[:new_password], password_confirmation: attrs[:new_password_confirmation])
  end

  def gravatar_image_url
    "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end

  def display_name
    if name.present?
      name 
    else
      "Author"
    end
  end

  private

  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :date
#

class Post < ApplicationRecord
  mount_uploader :banner_image_url, ImageUploader
  mount_uploaders :attachments, ImageUploader

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :author

  PER_PAGE = 9

  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  scope :whereauthor, -> (author_id) { where(author_id: author_id) if author_id.present? }

  scope :list_for, -> (page, author_id, tag) do
      recent_paginated(page).whereauthor(author_id).with_tag(tag)
  end

  def should_generate_new_friendly_id?
  	title_changed?
  end

  def display_day_published
    if published_at.present?
      "#{published_at.strftime('%-b %-d, %Y')}"
    else
      "Not published yet."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end
  
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!

end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController

    def edit
      
    end

    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Successfully saved info'
      else
        flash[:danger] = current_author.display_error_messages
      end
      redirect_to authors_account_path
    end

    def change_password 
      author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.change_password(author_password_params)
          sign_in(author, bypass: true)
          flash[:success] = 'Successfully changed password'
        else
          flash[:danger] = author.display_error_messages
        end
      else
        flash[:danger] = "Current password war incorrect"
      end
      redirect_to authors_account_path
    end

    private

    def author_info_params
      params.require(:author).permit(:name, :email, :bio)
    end

    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end

  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.post.most_recent.paginate(:page => params[:page], per_page: 20)
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.post.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list, :remove_banner_image_url,  :width, :height, :frames, :speed, attachments: [])
      end
  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index
      puts params.inspect
      @posts = storage.list_for(params[:page], params[:author_id], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end

  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<div class="row">
  <%= form_for(post, url: url) do |f| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-block">
          <% if @post.new_record? %>
            <h4 class="card-title">New Post</h4>
          <% else %>
            <h4 class="card-title">
              <b>Edit</b>
              <span class="thin-text"><%= @post.title %></span>
            </h4>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :banner_image_url %>
              <%= f.file_field :banner_image_url, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :attachments %>
              <%= f.file_field :attachments, multiple: true %>
            </div>
          </li>

          <li class="list-group-item">
            <div class="row">
              <div class="col-xs-6">
                <%= f.label :width %>
                <%= f.text_field :width, class: 'form-control' %>
              </div>
              <div class="col-xs-6">
                <%= f.label :height %>
                <%= f.text_field :height, class: 'form-control' %>
              </div>
            </div>
          </li>

          <li class="list-group-item">
            <div class="row">
              <div class="col-xs-6">
                <%= f.label :frames %>
                <%= f.text_field :frames, class: 'form-control' %>
              </div>
              <div class="col-xs-6">
                <%= f.label :speed %>
                <%= f.text_field :speed, class: 'form-control' %>
              </div>
            </div>  
          </li>

          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Tags' %>
              <%= f.text_area :tag_list, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <div class="actions">
                <%= f.submit "Save post", class: 'btn btn-success btn-md btn-block'%>
              </div>
            </div>            
          </li>
        </ul>
      </div>
      <% if @post.persisted?%>
        <%= link_to 'Show', @post, class: 'btn btn-sm btn-info' %> 
      <% end %>
      <%= link_to 'Back', authors_posts_path, class: 'btn btn-sm btn-info' %>
    </div>

    <div class="col-md-8">
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>
    </div>
  <% end %>
</div>

app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
  <% if post.published? %>
    <td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %></td>
  <% else %>
    <td><%= link_to 'Publish', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %></td>
  <% end %>
  <td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_post_url %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, "All Posts") %>
<% provide(:author, 'active') %>

<div class="row">
  <div>
    <%= link_to 'New post', new_authors_post_path, class: 'btn btn-primary btn-lg' %>
  </div>
  <br>
	<table class="table table-striped">
    <tr>
      <th colspan = "4">Title</th>
    </tr>
    <%= render @posts %>
    <div class="apple_pagination">
      <%= will_paginate @posts, container: false %>
    </div>
  </table>
</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, "New Post") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_posts_url(@post) %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div class="row">
  <%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
  <%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  <%= link_to 'Back', authors_posts_path, class: 'btn btn-sm btn-info' %>
</div>

<div class="row">
  <div class="col-md-1 col-lg-2">
    
  </div>
  <div class="col-md-10 col-lg-8 text-center">
    <h1><%= @post.title %></h1>
    <h5><%= @post.display_day_published %></h5>
    <%= @post.body.html_safe %>
    <img id="image" src="/uploads/<%= @post.id%>/untitled.1.jpg" width="<%= @post.width%>" height="<%= @post.height%>" />
  </div>
  <script>
    $(function(){ // when DOM ready
      var check = false;
      $('#image').mouseover(function() {
        if (check == false)
        {
          reel();
          check = true;
        }
      });
      var reel = function() {
        $('#image').reel({
          images:      '/uploads/<%= @post.id%>/untitled.#.jpg',
          frames:      '<%= @post.frames%>',
          loops:       true,
          speed:       '<%= @post.speed%>',
          cw:          true,
        });
      }
    });
  </script>
</div>