config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  root to: 'blog/posts#index'

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
  	resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
  	get 'about' => 'pages#about', as: :about
  	get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-top <%= request.original_url == root_url ? 'in-home' : 'not-home' %>">
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
    <div class="icon-blog">
      <svg viewBox="0 0 508.52 508.52" style="enable-background:new 0 0 508.52 508.52;" width="40px" height="40px"><path d="M254.26,0C113.845,0,0,113.845,0,254.26s113.845,254.26,254.26,254.26      s254.26-113.845,254.26-254.26C508.52,113.813,394.675,0,254.26,0z M412.727,310.451c0,56.509-45.989,102.308-102.943,102.308      H198.831c-56.891,0-103.102-45.735-103.102-102.308V198.132c0.032-56.541,46.18-102.371,103.102-102.371h51.964      c56.954,0,102.53,42.525,102.53,99.066c0.731,10.584,10.298,19.8,21.167,19.8h17.766c11.378,0,20.5,11.95,20.5,23.233      L412.727,310.451L412.727,310.451z" fill="<%= request.original_url == root_url ? '#000000' : '#FFFFFF' %>"/>
      <path d="M313.693,293.893H194.827c-10.901,0-19.8,8.899-19.8,19.801c0,10.87,8.931,19.8,19.8,19.8      h118.866c10.901,0,19.8-8.931,19.8-19.8C333.494,302.792,324.594,293.893,313.693,293.893z" fill="<%= request.original_url == root_url ? '#000000' : '#FFFFFF' %>"/>
      <path d="M194.827,214.627h59.433c10.901,0,19.8-8.931,19.8-19.8c0-10.901-8.931-19.8-19.8-19.8h-59.433      c-10.901,0-19.8,8.931-19.8,19.8C174.994,205.728,183.925,214.627,194.827,214.627z" fill="<%= request.original_url == root_url ? '#000000' : '#FFFFFF' %>"/>
      </svg>
    </div>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if author_signed_in? %>
        <li class="author-nav">
            <a href="#" class="dropdown-toggle nav-link <%= yield(:author) %>" id="navbarDropdownMenuLink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag(current_author.gravatar_image_url) %>
              <%= current_author.display_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <%= link_to 'My posts', authors_posts_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Account', authors_account_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
      <% else %>
        <li class="nav-item sign-in">
          <%= link_to 'Sign in', new_author_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<% if request.original_url == root_url %>

  <div class="back_nav">
  </div>
<% end %>
<nav class="navbar navbar-bottom <%= request.original_url == root_url ? 'in-home' : 'not-home' %>">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <a class='navbar-brand' href='/'>
      The<span class='light'>Rings</span>
    </a>

    <ul class="nav navbar-nav navbar-left">
      <%= link_to 'Diamond', posts_path(tag: 'Dimond'), class: "nav-link" %>
      <%= link_to 'Silver', posts_path(tag: 'silver'), class: "nav-link" %>
      <!-- <%= link_to 'Music', posts_path(tag: 'music'), class: "nav-link" %> -->
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <a class="svgIcon" href="https://twitter.com/NguynHo66189771">
        <svg class="svgIcon-use" width="30" height="30" viewBox="0 0 25 25"><path d="M21.725 5.338c-.744.47-1.605.804-2.513 1.006a3.978 3.978 0 0 0-2.942-1.293c-2.22 0-4.02 1.81-4.02 4.02 0 .32.034.63.07.94-3.31-.18-6.27-1.78-8.255-4.23a4.544 4.544 0 0 0-.574 2.01c.04 1.43.74 2.66 1.8 3.38-.63-.01-1.25-.19-1.79-.5v.08c0 1.93 1.38 3.56 3.23 3.95-.34.07-.7.12-1.07.14-.25-.02-.5-.04-.72-.07.49 1.58 1.97 2.74 3.74 2.8a8.49 8.49 0 0 1-5.02 1.72c-.3-.03-.62-.04-.93-.07A11.447 11.447 0 0 0 8.88 21c7.386 0 11.43-6.13 11.414-11.414.015-.21.01-.38 0-.578a7.604 7.604 0 0 0 2.01-2.08 7.27 7.27 0 0 1-2.297.645 3.856 3.856 0 0 0 1.72-2.23" fill="#FFFFFF"></path></svg>
      </a>
      <a class="svgIcon" href="https://www.facebook.com/DwThien">
        <svg class="svgIcon-use" width="30" height="30" viewBox="0 0 25 25"><path d="M21 12.646C21 7.65 16.97 3.6 12 3.6s-9 4.05-9 9.046a9.026 9.026 0 0 0 7.59 8.924v-6.376H8.395V12.64h2.193v-1.88c0-2.186 1.328-3.375 3.267-3.375.93 0 1.728.07 1.96.1V9.77H14.47c-1.055 0-1.26.503-1.26 1.242v1.63h2.517l-.33 2.554H13.21V21.6c4.398-.597 7.79-4.373 7.79-8.954" fill="#FFFFFF"></path></svg>
      </a>
    </ul>
  </div><!-- /.container-fluid -->
</nav>
<script type="text/javascript">
  $(document).ready(function(){
    $('a[href="' + location.pathname+location.search + '"]').addClass('active');
  });
</script>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %> | Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=m6xj5bldga95p3ylk7qoaenpcx7d0ad3s3cttfl0b7c5nxs0"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <% if flash.any? %>
        <% flash.keys.each do |key| %>
          <div class="alert alert-<%= key.to_s %> alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= flash[key] %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>